/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Admin {
  'principal' : Principal,
  'role' : AdminRole,
  'email' : [] | [string],
  'addedAt' : Timestamp,
  'isOwner' : boolean,
}
export type AdminRole = { 'owner' : null } |
  { 'editor' : null } |
  { 'viewer' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface ContactInput {
  'name' : string,
  'email' : string,
  'message' : string,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export interface Faq {
  'id' : Id,
  'question' : string,
  'sortOrder' : bigint,
  'createdAt' : Timestamp,
  'answer' : string,
  'updatedAt' : Timestamp,
  'state' : PublishState,
}
export interface FaqInput {
  'question' : string,
  'sortOrder' : bigint,
  'answer' : string,
}
export interface FaqPatch {
  'question' : [] | [string],
  'sortOrder' : [] | [bigint],
  'answer' : [] | [string],
}
export type Id = bigint;
export interface Product {
  'id' : Id,
  'sortOrder' : bigint,
  'link' : [] | [string],
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'state' : PublishState,
  'imageKey' : [] | [ExternalBlob],
}
export interface ProductInput {
  'sortOrder' : bigint,
  'link' : [] | [string],
  'name' : string,
  'description' : string,
  'imageKey' : [] | [ExternalBlob],
}
export interface ProductPatch {
  'sortOrder' : [] | [bigint],
  'link' : [] | [string],
  'name' : [] | [string],
  'description' : [] | [string],
  'imageKey' : [] | [ExternalBlob],
}
export type PublishState = { 'published' : null } |
  { 'draft' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface SiteContent {
  'contactBody' : [] | [string],
  'privacyBody' : [] | [string],
  'heroDescription' : [] | [string],
  'primaryCtaHref' : [] | [string],
  'primaryCtaLabel' : [] | [string],
  'philosophyTitle' : [] | [string],
  'contactTitle' : [] | [string],
  'philosophyBody' : [] | [string],
  'aboutTitle' : [] | [string],
  'waitlistTitle' : [] | [string],
  'secondaryCtaHref' : [] | [string],
  'updatedAt' : Timestamp,
  'approachBody' : [] | [string],
  'aboutBody' : [] | [string],
  'termsBody' : [] | [string],
  'approachTitle' : [] | [string],
  'heroHeadline' : [] | [string],
  'secondaryCtaLabel' : [] | [string],
  'footerText' : [] | [string],
  'waitlistBody' : [] | [string],
}
export interface SiteContentPatch {
  'contactBody' : [] | [string],
  'privacyBody' : [] | [string],
  'heroDescription' : [] | [string],
  'primaryCtaHref' : [] | [string],
  'primaryCtaLabel' : [] | [string],
  'philosophyTitle' : [] | [string],
  'contactTitle' : [] | [string],
  'philosophyBody' : [] | [string],
  'aboutTitle' : [] | [string],
  'waitlistTitle' : [] | [string],
  'secondaryCtaHref' : [] | [string],
  'approachBody' : [] | [string],
  'aboutBody' : [] | [string],
  'termsBody' : [] | [string],
  'approachTitle' : [] | [string],
  'heroHeadline' : [] | [string],
  'secondaryCtaLabel' : [] | [string],
  'footerText' : [] | [string],
  'waitlistBody' : [] | [string],
}
export interface Submission {
  'id' : Id,
  'status' : SubmissionStatus,
  'kind' : SubmissionKind,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'updatedAt' : Timestamp,
  'message' : [] | [string],
}
export interface SubmissionFilter {
  'status' : [] | [SubmissionStatus],
  'kind' : [] | [SubmissionKind],
}
export type SubmissionKind = { 'contact' : null } |
  { 'waitlist' : null };
export type SubmissionStatus = { 'new' : null } |
  { 'handled' : null } |
  { 'read' : null };
export type SubmitResult = { 'created' : Submission } |
  { 'duplicate' : Submission };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface WaitlistInput {
  'name' : string,
  'note' : [] | [string],
  'email' : string,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Grants admin access to `principal` with `role`. Owner only.
   */
  'addAdmin' : ActorMethod<[Principal, AdminRole], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / One-time ownership bootstrap. Succeeds only when no owner exists yet and
   * / `email` matches the configured owner email. After the owner exists this
   * / always returns `false`, so no caller can self-grant admin access.
   */
  'claimOwner' : ActorMethod<[string], boolean>,
  /**
   * / Creates an FAQ. Admin only.
   */
  'createFaq' : ActorMethod<[FaqInput], Faq>,
  /**
   * / Creates a product. Admin only.
   */
  'createProduct' : ActorMethod<[ProductInput], Product>,
  /**
   * / Deletes an FAQ. Admin only.
   */
  'deleteFaq' : ActorMethod<[bigint], boolean>,
  /**
   * / Deletes a product. Admin only.
   */
  'deleteProduct' : ActorMethod<[bigint], boolean>,
  /**
   * / Deletes a submission. Admin only.
   */
  'deleteSubmission' : ActorMethod<[bigint], boolean>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Returns the backend's public API documentation as Markdown.
   */
  'getApiDoc' : ActorMethod<[], string>,
  /**
   * / Returns the caller's admin record, or `null` when not an admin.
   */
  'getCallerAdmin' : ActorMethod<[], [] | [Admin]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / A single FAQ by id. Admin only.
   */
  'getFaq' : ActorMethod<[bigint], [] | [Faq]>,
  /**
   * / A single product by id. Admin only.
   */
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  /**
   * / Editable site copy for the public website.
   */
  'getSiteContent' : ActorMethod<[], SiteContent>,
  /**
   * / A single submission by id. Admin only.
   */
  'getSubmission' : ActorMethod<[bigint], [] | [Submission]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Returns whether the caller is the owner.
   */
  'isCallerOwner' : ActorMethod<[], boolean>,
  /**
   * / Returns whether the owner has been claimed yet. While this is `false`,
   * / `claimOwner` is open to the configured owner email.
   */
  'isOwnerClaimed' : ActorMethod<[], boolean>,
  /**
   * / Every admin. Admin only.
   */
  'listAdmins' : ActorMethod<[], Array<Admin>>,
  /**
   * / Every FAQ, published or not. Admin only.
   */
  'listAllFaqs' : ActorMethod<[], Array<Faq>>,
  /**
   * / Every product, published or not. Admin only.
   */
  'listAllProducts' : ActorMethod<[], Array<Product>>,
  /**
   * / Up to `limit` published FAQs in admin-defined order.
   */
  'listPublishedFaqs' : ActorMethod<[bigint], Array<Faq>>,
  /**
   * / Published products in admin-defined order.
   */
  'listPublishedProducts' : ActorMethod<[], Array<Product>>,
  /**
   * / Submissions matching `filter`, newest first. Admin only.
   */
  'listSubmissions' : ActorMethod<[SubmissionFilter], Array<Submission>>,
  /**
   * / Revokes admin access from `principal`. Owner only; the owner cannot be
   * / removed.
   */
  'removeAdmin' : ActorMethod<[Principal], boolean>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Changes an admin's role. Owner only; the owner's own role cannot change.
   */
  'setAdminRole' : ActorMethod<[Principal, AdminRole], [] | [Admin]>,
  /**
   * / Publishes or unpublishes an FAQ. Admin only.
   */
  'setFaqState' : ActorMethod<[bigint, PublishState], [] | [Faq]>,
  /**
   * / Publishes or unpublishes a product. Admin only.
   */
  'setProductState' : ActorMethod<[bigint, PublishState], [] | [Product]>,
  /**
   * / Sets a submission's review status. Admin only.
   */
  'setSubmissionStatus' : ActorMethod<
    [bigint, SubmissionStatus],
    [] | [Submission]
  >,
  /**
   * / Stores a Contact submission. Callable by anyone, including anonymous.
   * / Returns `#created` with the new record, or `#duplicate` with the existing
   * / record when the same normalized email and message were already received.
   */
  'submitContact' : ActorMethod<[ContactInput], SubmitResult>,
  /**
   * / Stores a Waitlist submission. Callable by anyone, including anonymous.
   * / Returns `#created` with the new record, or `#duplicate` with the existing
   * / record when the same normalized email and note were already received.
   */
  'submitWaitlist' : ActorMethod<[WaitlistInput], SubmitResult>,
  /**
   * / Applies a partial update to an FAQ. Admin only.
   */
  'updateFaq' : ActorMethod<[bigint, FaqPatch], [] | [Faq]>,
  /**
   * / Applies a partial update to a product. Admin only.
   */
  'updateProduct' : ActorMethod<[bigint, ProductPatch], [] | [Product]>,
  /**
   * / Merges a partial patch into the editable site copy. Admin only.
   */
  'updateSiteContent' : ActorMethod<[SiteContentPatch], SiteContent>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];