/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const AdminRole = IDL.Variant({
  'owner' : IDL.Null,
  'editor' : IDL.Null,
  'viewer' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FaqInput = IDL.Record({
  'question' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'answer' : IDL.Text,
});
export const Id = IDL.Nat;
export const Timestamp = IDL.Nat;
export const PublishState = IDL.Variant({
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const Faq = IDL.Record({
  'id' : Id,
  'question' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'createdAt' : Timestamp,
  'answer' : IDL.Text,
  'updatedAt' : Timestamp,
  'state' : PublishState,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProductInput = IDL.Record({
  'sortOrder' : IDL.Nat,
  'link' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageKey' : IDL.Opt(ExternalBlob),
});
export const Product = IDL.Record({
  'id' : Id,
  'sortOrder' : IDL.Nat,
  'link' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'state' : PublishState,
  'imageKey' : IDL.Opt(ExternalBlob),
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Admin = IDL.Record({
  'principal' : IDL.Principal,
  'role' : AdminRole,
  'email' : IDL.Opt(IDL.Text),
  'addedAt' : Timestamp,
  'isOwner' : IDL.Bool,
});
export const RoutePath = IDL.Text;
export const RouteViews = IDL.Record({
  'lastSeenAt' : Timestamp,
  'views' : IDL.Nat,
  'firstSeenAt' : Timestamp,
  'path' : RoutePath,
});
export const SiteContent = IDL.Record({
  'contactBody' : IDL.Opt(IDL.Text),
  'privacyBody' : IDL.Opt(IDL.Text),
  'heroDescription' : IDL.Opt(IDL.Text),
  'primaryCtaHref' : IDL.Opt(IDL.Text),
  'primaryCtaLabel' : IDL.Opt(IDL.Text),
  'philosophyTitle' : IDL.Opt(IDL.Text),
  'contactTitle' : IDL.Opt(IDL.Text),
  'philosophyBody' : IDL.Opt(IDL.Text),
  'aboutTitle' : IDL.Opt(IDL.Text),
  'waitlistTitle' : IDL.Opt(IDL.Text),
  'secondaryCtaHref' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'approachBody' : IDL.Opt(IDL.Text),
  'aboutBody' : IDL.Opt(IDL.Text),
  'termsBody' : IDL.Opt(IDL.Text),
  'approachTitle' : IDL.Opt(IDL.Text),
  'heroHeadline' : IDL.Opt(IDL.Text),
  'secondaryCtaLabel' : IDL.Opt(IDL.Text),
  'footerText' : IDL.Opt(IDL.Text),
  'waitlistBody' : IDL.Opt(IDL.Text),
});
export const SubmissionStatus = IDL.Variant({
  'new' : IDL.Null,
  'handled' : IDL.Null,
  'read' : IDL.Null,
});
export const SubmissionKind = IDL.Variant({
  'contact' : IDL.Null,
  'waitlist' : IDL.Null,
});
export const Submission = IDL.Record({
  'id' : Id,
  'status' : SubmissionStatus,
  'kind' : SubmissionKind,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'updatedAt' : Timestamp,
  'message' : IDL.Opt(IDL.Text),
});
export const SubmissionFilter = IDL.Record({
  'status' : IDL.Opt(SubmissionStatus),
  'kind' : IDL.Opt(SubmissionKind),
});
export const RecordViewResult = IDL.Variant({
  'recorded' : RouteViews,
  'ignored' : IDL.Null,
});
export const ContactInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const SubmitResult = IDL.Variant({
  'created' : Submission,
  'duplicate' : Submission,
});
export const WaitlistInput = IDL.Record({
  'name' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
});
export const FaqPatch = IDL.Record({
  'question' : IDL.Opt(IDL.Text),
  'sortOrder' : IDL.Opt(IDL.Nat),
  'answer' : IDL.Opt(IDL.Text),
});
export const ProductPatch = IDL.Record({
  'sortOrder' : IDL.Opt(IDL.Nat),
  'link' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'imageKey' : IDL.Opt(ExternalBlob),
});
export const SiteContentPatch = IDL.Record({
  'contactBody' : IDL.Opt(IDL.Text),
  'privacyBody' : IDL.Opt(IDL.Text),
  'heroDescription' : IDL.Opt(IDL.Text),
  'primaryCtaHref' : IDL.Opt(IDL.Text),
  'primaryCtaLabel' : IDL.Opt(IDL.Text),
  'philosophyTitle' : IDL.Opt(IDL.Text),
  'contactTitle' : IDL.Opt(IDL.Text),
  'philosophyBody' : IDL.Opt(IDL.Text),
  'aboutTitle' : IDL.Opt(IDL.Text),
  'waitlistTitle' : IDL.Opt(IDL.Text),
  'secondaryCtaHref' : IDL.Opt(IDL.Text),
  'approachBody' : IDL.Opt(IDL.Text),
  'aboutBody' : IDL.Opt(IDL.Text),
  'termsBody' : IDL.Opt(IDL.Text),
  'approachTitle' : IDL.Opt(IDL.Text),
  'heroHeadline' : IDL.Opt(IDL.Text),
  'secondaryCtaLabel' : IDL.Opt(IDL.Text),
  'footerText' : IDL.Opt(IDL.Text),
  'waitlistBody' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addAdmin' : IDL.Func([IDL.Principal, AdminRole], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimOwner' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createFaq' : IDL.Func([FaqInput], [Faq], []),
  'createProduct' : IDL.Func([ProductInput], [Product], []),
  'deleteFaq' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteSubmission' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerAdmin' : IDL.Func([], [IDL.Opt(Admin)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFaq' : IDL.Func([IDL.Nat], [IDL.Opt(Faq)], ['query']),
  'getPageViews' : IDL.Func([IDL.Text], [IDL.Opt(RouteViews)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
  'getSubmission' : IDL.Func([IDL.Nat], [IDL.Opt(Submission)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerOwner' : IDL.Func([], [IDL.Bool], ['query']),
  'isOwnerClaimed' : IDL.Func([], [IDL.Bool], ['query']),
  'listAdmins' : IDL.Func([], [IDL.Vec(Admin)], ['query']),
  'listAllFaqs' : IDL.Func([], [IDL.Vec(Faq)], ['query']),
  'listAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listPageViews' : IDL.Func([], [IDL.Vec(RouteViews)], ['query']),
  'listPublishedFaqs' : IDL.Func([IDL.Nat], [IDL.Vec(Faq)], ['query']),
  'listPublishedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listSubmissions' : IDL.Func(
      [SubmissionFilter],
      [IDL.Vec(Submission)],
      ['query'],
    ),
  'recordPageView' : IDL.Func([IDL.Text], [RecordViewResult], []),
  'removeAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setAdminRole' : IDL.Func([IDL.Principal, AdminRole], [IDL.Opt(Admin)], []),
  'setFaqState' : IDL.Func([IDL.Nat, PublishState], [IDL.Opt(Faq)], []),
  'setProductState' : IDL.Func([IDL.Nat, PublishState], [IDL.Opt(Product)], []),
  'setSubmissionStatus' : IDL.Func(
      [IDL.Nat, SubmissionStatus],
      [IDL.Opt(Submission)],
      [],
    ),
  'submitContact' : IDL.Func([ContactInput], [SubmitResult], []),
  'submitWaitlist' : IDL.Func([WaitlistInput], [SubmitResult], []),
  'updateFaq' : IDL.Func([IDL.Nat, FaqPatch], [IDL.Opt(Faq)], []),
  'updateProduct' : IDL.Func([IDL.Nat, ProductPatch], [IDL.Opt(Product)], []),
  'updateSiteContent' : IDL.Func([SiteContentPatch], [SiteContent], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const AdminRole = IDL.Variant({
    'owner' : IDL.Null,
    'editor' : IDL.Null,
    'viewer' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FaqInput = IDL.Record({
    'question' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'answer' : IDL.Text,
  });
  const Id = IDL.Nat;
  const Timestamp = IDL.Nat;
  const PublishState = IDL.Variant({
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Faq = IDL.Record({
    'id' : Id,
    'question' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'createdAt' : Timestamp,
    'answer' : IDL.Text,
    'updatedAt' : Timestamp,
    'state' : PublishState,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProductInput = IDL.Record({
    'sortOrder' : IDL.Nat,
    'link' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageKey' : IDL.Opt(ExternalBlob),
  });
  const Product = IDL.Record({
    'id' : Id,
    'sortOrder' : IDL.Nat,
    'link' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'state' : PublishState,
    'imageKey' : IDL.Opt(ExternalBlob),
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Admin = IDL.Record({
    'principal' : IDL.Principal,
    'role' : AdminRole,
    'email' : IDL.Opt(IDL.Text),
    'addedAt' : Timestamp,
    'isOwner' : IDL.Bool,
  });
  const RoutePath = IDL.Text;
  const RouteViews = IDL.Record({
    'lastSeenAt' : Timestamp,
    'views' : IDL.Nat,
    'firstSeenAt' : Timestamp,
    'path' : RoutePath,
  });
  const SiteContent = IDL.Record({
    'contactBody' : IDL.Opt(IDL.Text),
    'privacyBody' : IDL.Opt(IDL.Text),
    'heroDescription' : IDL.Opt(IDL.Text),
    'primaryCtaHref' : IDL.Opt(IDL.Text),
    'primaryCtaLabel' : IDL.Opt(IDL.Text),
    'philosophyTitle' : IDL.Opt(IDL.Text),
    'contactTitle' : IDL.Opt(IDL.Text),
    'philosophyBody' : IDL.Opt(IDL.Text),
    'aboutTitle' : IDL.Opt(IDL.Text),
    'waitlistTitle' : IDL.Opt(IDL.Text),
    'secondaryCtaHref' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'approachBody' : IDL.Opt(IDL.Text),
    'aboutBody' : IDL.Opt(IDL.Text),
    'termsBody' : IDL.Opt(IDL.Text),
    'approachTitle' : IDL.Opt(IDL.Text),
    'heroHeadline' : IDL.Opt(IDL.Text),
    'secondaryCtaLabel' : IDL.Opt(IDL.Text),
    'footerText' : IDL.Opt(IDL.Text),
    'waitlistBody' : IDL.Opt(IDL.Text),
  });
  const SubmissionStatus = IDL.Variant({
    'new' : IDL.Null,
    'handled' : IDL.Null,
    'read' : IDL.Null,
  });
  const SubmissionKind = IDL.Variant({
    'contact' : IDL.Null,
    'waitlist' : IDL.Null,
  });
  const Submission = IDL.Record({
    'id' : Id,
    'status' : SubmissionStatus,
    'kind' : SubmissionKind,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'updatedAt' : Timestamp,
    'message' : IDL.Opt(IDL.Text),
  });
  const SubmissionFilter = IDL.Record({
    'status' : IDL.Opt(SubmissionStatus),
    'kind' : IDL.Opt(SubmissionKind),
  });
  const RecordViewResult = IDL.Variant({
    'recorded' : RouteViews,
    'ignored' : IDL.Null,
  });
  const ContactInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const SubmitResult = IDL.Variant({
    'created' : Submission,
    'duplicate' : Submission,
  });
  const WaitlistInput = IDL.Record({
    'name' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
  });
  const FaqPatch = IDL.Record({
    'question' : IDL.Opt(IDL.Text),
    'sortOrder' : IDL.Opt(IDL.Nat),
    'answer' : IDL.Opt(IDL.Text),
  });
  const ProductPatch = IDL.Record({
    'sortOrder' : IDL.Opt(IDL.Nat),
    'link' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'imageKey' : IDL.Opt(ExternalBlob),
  });
  const SiteContentPatch = IDL.Record({
    'contactBody' : IDL.Opt(IDL.Text),
    'privacyBody' : IDL.Opt(IDL.Text),
    'heroDescription' : IDL.Opt(IDL.Text),
    'primaryCtaHref' : IDL.Opt(IDL.Text),
    'primaryCtaLabel' : IDL.Opt(IDL.Text),
    'philosophyTitle' : IDL.Opt(IDL.Text),
    'contactTitle' : IDL.Opt(IDL.Text),
    'philosophyBody' : IDL.Opt(IDL.Text),
    'aboutTitle' : IDL.Opt(IDL.Text),
    'waitlistTitle' : IDL.Opt(IDL.Text),
    'secondaryCtaHref' : IDL.Opt(IDL.Text),
    'approachBody' : IDL.Opt(IDL.Text),
    'aboutBody' : IDL.Opt(IDL.Text),
    'termsBody' : IDL.Opt(IDL.Text),
    'approachTitle' : IDL.Opt(IDL.Text),
    'heroHeadline' : IDL.Opt(IDL.Text),
    'secondaryCtaLabel' : IDL.Opt(IDL.Text),
    'footerText' : IDL.Opt(IDL.Text),
    'waitlistBody' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addAdmin' : IDL.Func([IDL.Principal, AdminRole], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimOwner' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createFaq' : IDL.Func([FaqInput], [Faq], []),
    'createProduct' : IDL.Func([ProductInput], [Product], []),
    'deleteFaq' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteSubmission' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerAdmin' : IDL.Func([], [IDL.Opt(Admin)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFaq' : IDL.Func([IDL.Nat], [IDL.Opt(Faq)], ['query']),
    'getPageViews' : IDL.Func([IDL.Text], [IDL.Opt(RouteViews)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
    'getSubmission' : IDL.Func([IDL.Nat], [IDL.Opt(Submission)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerOwner' : IDL.Func([], [IDL.Bool], ['query']),
    'isOwnerClaimed' : IDL.Func([], [IDL.Bool], ['query']),
    'listAdmins' : IDL.Func([], [IDL.Vec(Admin)], ['query']),
    'listAllFaqs' : IDL.Func([], [IDL.Vec(Faq)], ['query']),
    'listAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listPageViews' : IDL.Func([], [IDL.Vec(RouteViews)], ['query']),
    'listPublishedFaqs' : IDL.Func([IDL.Nat], [IDL.Vec(Faq)], ['query']),
    'listPublishedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listSubmissions' : IDL.Func(
        [SubmissionFilter],
        [IDL.Vec(Submission)],
        ['query'],
      ),
    'recordPageView' : IDL.Func([IDL.Text], [RecordViewResult], []),
    'removeAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setAdminRole' : IDL.Func([IDL.Principal, AdminRole], [IDL.Opt(Admin)], []),
    'setFaqState' : IDL.Func([IDL.Nat, PublishState], [IDL.Opt(Faq)], []),
    'setProductState' : IDL.Func(
        [IDL.Nat, PublishState],
        [IDL.Opt(Product)],
        [],
      ),
    'setSubmissionStatus' : IDL.Func(
        [IDL.Nat, SubmissionStatus],
        [IDL.Opt(Submission)],
        [],
      ),
    'submitContact' : IDL.Func([ContactInput], [SubmitResult], []),
    'submitWaitlist' : IDL.Func([WaitlistInput], [SubmitResult], []),
    'updateFaq' : IDL.Func([IDL.Nat, FaqPatch], [IDL.Opt(Faq)], []),
    'updateProduct' : IDL.Func([IDL.Nat, ProductPatch], [IDL.Opt(Product)], []),
    'updateSiteContent' : IDL.Func([SiteContentPatch], [SiteContent], []),
  });
};

export const init = ({ IDL }) => { return []; };