/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Admin {
    principal: Principal;
    role: AdminRole;
    email?: string;
    addedAt: Timestamp;
    isOwner: boolean;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface ContactInput {
    name: string;
    email: string;
    message: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Faq {
    id: Id;
    question: string;
    sortOrder: bigint;
    createdAt: Timestamp;
    answer: string;
    updatedAt: Timestamp;
    state: PublishState;
}
export interface FaqInput {
    question: string;
    sortOrder: bigint;
    answer: string;
}
export interface FaqPatch {
    question?: string;
    sortOrder?: bigint;
    answer?: string;
}
export type Id = bigint;
export interface Product {
    id: Id;
    sortOrder: bigint;
    link?: string;
    name: string;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    state: PublishState;
    imageKey?: ExternalBlob;
}
export interface ProductInput {
    sortOrder: bigint;
    link?: string;
    name: string;
    description: string;
    imageKey?: ExternalBlob;
}
export interface ProductPatch {
    sortOrder?: bigint;
    link?: string;
    name?: string;
    description?: string;
    imageKey?: ExternalBlob;
}
export type RecordViewResult = {
    __kind__: "recorded";
    recorded: RouteViews;
} | {
    __kind__: "ignored";
    ignored: null;
};
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type RoutePath = string;
export interface RouteViews {
    lastSeenAt: Timestamp;
    views: bigint;
    firstSeenAt: Timestamp;
    path: RoutePath;
}
export interface SiteContent {
    contactBody?: string;
    privacyBody?: string;
    heroDescription?: string;
    primaryCtaHref?: string;
    primaryCtaLabel?: string;
    philosophyTitle?: string;
    contactTitle?: string;
    philosophyBody?: string;
    aboutTitle?: string;
    waitlistTitle?: string;
    secondaryCtaHref?: string;
    updatedAt: Timestamp;
    approachBody?: string;
    aboutBody?: string;
    termsBody?: string;
    approachTitle?: string;
    heroHeadline?: string;
    secondaryCtaLabel?: string;
    footerText?: string;
    waitlistBody?: string;
}
export interface SiteContentPatch {
    contactBody?: string;
    privacyBody?: string;
    heroDescription?: string;
    primaryCtaHref?: string;
    primaryCtaLabel?: string;
    philosophyTitle?: string;
    contactTitle?: string;
    philosophyBody?: string;
    aboutTitle?: string;
    waitlistTitle?: string;
    secondaryCtaHref?: string;
    approachBody?: string;
    aboutBody?: string;
    termsBody?: string;
    approachTitle?: string;
    heroHeadline?: string;
    secondaryCtaLabel?: string;
    footerText?: string;
    waitlistBody?: string;
}
export interface Submission {
    id: Id;
    status: SubmissionStatus;
    kind: SubmissionKind;
    name: string;
    createdAt: Timestamp;
    email: string;
    updatedAt: Timestamp;
    message?: string;
}
export interface SubmissionFilter {
    status?: SubmissionStatus;
    kind?: SubmissionKind;
}
export type SubmitResult = {
    __kind__: "created";
    created: Submission;
} | {
    __kind__: "duplicate";
    duplicate: Submission;
};
export type Timestamp = bigint;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface WaitlistInput {
    name: string;
    note?: string;
    email: string;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AdminRole {
    owner = "owner",
    editor = "editor",
    viewer = "viewer"
}
export enum PublishState {
    published = "published",
    draft = "draft"
}
export enum SubmissionKind {
    contact = "contact",
    waitlist = "waitlist"
}
export enum SubmissionStatus {
    new_ = "new",
    handled = "handled",
    read = "read"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    /**
     * / Grants admin access to `principal` with `role`. Owner only.
     */
    addAdmin(principal: Principal, role: AdminRole): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / One-time ownership bootstrap. Succeeds only when no owner exists yet and
     * / `email` matches the configured owner email. After the owner exists this
     * / always returns `false`, so no caller can self-grant admin access.
     */
    claimOwner(email: string): Promise<boolean>;
    /**
     * / Creates an FAQ. Admin only.
     */
    createFaq(input: FaqInput): Promise<Faq>;
    /**
     * / Creates a product. Admin only.
     */
    createProduct(input: ProductInput): Promise<Product>;
    /**
     * / Deletes an FAQ. Admin only.
     */
    deleteFaq(id: bigint): Promise<boolean>;
    /**
     * / Deletes a product. Admin only.
     */
    deleteProduct(id: bigint): Promise<boolean>;
    /**
     * / Deletes a submission. Admin only.
     */
    deleteSubmission(id: bigint): Promise<boolean>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Returns the backend's public API documentation as Markdown.
     */
    getApiDoc(): Promise<string>;
    /**
     * / Returns the caller's admin record, or `null` when not an admin.
     */
    getCallerAdmin(): Promise<Admin | null>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / A single FAQ by id. Admin only.
     */
    getFaq(id: bigint): Promise<Faq | null>;
    /**
     * / Returns the aggregate view total for a single route, or `null` when the
     * / route has never been recorded.
     */
    getPageViews(path: string): Promise<RouteViews | null>;
    /**
     * / A single product by id. Admin only.
     */
    getProduct(id: bigint): Promise<Product | null>;
    /**
     * / Editable site copy for the public website.
     */
    getSiteContent(): Promise<SiteContent>;
    /**
     * / A single submission by id. Admin only.
     */
    getSubmission(id: bigint): Promise<Submission | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Returns whether the caller is the owner.
     */
    isCallerOwner(): Promise<boolean>;
    /**
     * / Returns whether the owner has been claimed yet. While this is `false`,
     * / `claimOwner` is open to the configured owner email.
     */
    isOwnerClaimed(): Promise<boolean>;
    /**
     * / Every admin. Admin only.
     */
    listAdmins(): Promise<Array<Admin>>;
    /**
     * / Every FAQ, published or not. Admin only.
     */
    listAllFaqs(): Promise<Array<Faq>>;
    /**
     * / Every product, published or not. Admin only.
     */
    listAllProducts(): Promise<Array<Product>>;
    /**
     * / Returns every recorded route with its aggregate total, ordered by path.
     */
    listPageViews(): Promise<Array<RouteViews>>;
    /**
     * / Up to `limit` published FAQs in admin-defined order.
     */
    listPublishedFaqs(limit: bigint): Promise<Array<Faq>>;
    /**
     * / Published products in admin-defined order.
     */
    listPublishedProducts(): Promise<Array<Product>>;
    /**
     * / Submissions matching `filter`, newest first. Admin only.
     */
    listSubmissions(filter: SubmissionFilter): Promise<Array<Submission>>;
    /**
     * / Records one view of a public route. Callable by anyone, including
     * / anonymous callers, because the frontend only calls it after the visitor
     * / has consented to analytics.
     * /
     * / The path is normalized and validated by the backend; an invalid path or an
     * / admin route is ignored and stores nothing. The counter is additive and
     * / stores only an aggregate total — no IP, user agent, principal, or session
     * / identifier is ever read or stored.
     */
    recordPageView(path: string): Promise<RecordViewResult>;
    /**
     * / Revokes admin access from `principal`. Owner only; the owner cannot be
     * / removed.
     */
    removeAdmin(principal: Principal): Promise<boolean>;
    schema(): Promise<string>;
    /**
     * / Changes an admin's role. Owner only; the owner's own role cannot change.
     */
    setAdminRole(principal: Principal, role: AdminRole): Promise<Admin | null>;
    /**
     * / Publishes or unpublishes an FAQ. Admin only.
     */
    setFaqState(id: bigint, state: PublishState): Promise<Faq | null>;
    /**
     * / Publishes or unpublishes a product. Admin only.
     */
    setProductState(id: bigint, state: PublishState): Promise<Product | null>;
    /**
     * / Sets a submission's review status. Admin only.
     */
    setSubmissionStatus(id: bigint, status: SubmissionStatus): Promise<Submission | null>;
    /**
     * / Stores a Contact submission. Callable by anyone, including anonymous.
     * / Returns `#created` with the new record, or `#duplicate` with the existing
     * / record when the same normalized email and message were already received.
     */
    submitContact(input: ContactInput): Promise<SubmitResult>;
    /**
     * / Stores a Waitlist submission. Callable by anyone, including anonymous.
     * / Returns `#created` with the new record, or `#duplicate` with the existing
     * / record when the same normalized email and note were already received.
     */
    submitWaitlist(input: WaitlistInput): Promise<SubmitResult>;
    /**
     * / Applies a partial update to an FAQ. Admin only.
     */
    updateFaq(id: bigint, patch: FaqPatch): Promise<Faq | null>;
    /**
     * / Applies a partial update to a product. Admin only.
     */
    updateProduct(id: bigint, patch: ProductPatch): Promise<Product | null>;
    /**
     * / Merges a partial patch into the editable site copy. Admin only.
     */
    updateSiteContent(patch: SiteContentPatch): Promise<SiteContent>;
}
import type { Admin as _Admin, AdminRole as _AdminRole, Cell as _Cell, Error as _Error, ExternalBlob as _ExternalBlob, Faq as _Faq, FaqPatch as _FaqPatch, Id as _Id, Product as _Product, ProductInput as _ProductInput, ProductPatch as _ProductPatch, PublishState as _PublishState, RecordViewResult as _RecordViewResult, Result as _Result, Result__1 as _Result__1, RouteViews as _RouteViews, SiteContent as _SiteContent, SiteContentPatch as _SiteContentPatch, Submission as _Submission, SubmissionFilter as _SubmissionFilter, SubmissionKind as _SubmissionKind, SubmissionStatus as _SubmissionStatus, SubmitResult as _SubmitResult, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value, WaitlistInput as _WaitlistInput, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addAdmin(arg0: Principal, arg1: AdminRole): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdmin(arg0, to_candid_AdminRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdmin(arg0, to_candid_AdminRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimOwner(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimOwner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimOwner(arg0);
            return result;
        }
    }
    async createFaq(arg0: FaqInput): Promise<Faq> {
        if (this.processError) {
            try {
                const result = await this.actor.createFaq(arg0);
                return from_candid_Faq_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFaq(arg0);
            return from_candid_Faq_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProduct(arg0: ProductInput): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(await to_candid_ProductInput_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Product_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(await to_candid_ProductInput_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Product_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteFaq(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFaq(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFaq(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteSubmission(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubmission(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerAdmin(): Promise<Admin | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAdmin();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAdmin();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFaq(arg0: bigint): Promise<Faq | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFaq(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFaq(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPageViews(arg0: string): Promise<RouteViews | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPageViews(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPageViews(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiteContent(): Promise<SiteContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteContent();
                return from_candid_SiteContent_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteContent();
            return from_candid_SiteContent_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmission(arg0: bigint): Promise<Submission | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmission(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmission(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerOwner(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerOwner();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerOwner();
            return result;
        }
    }
    async isOwnerClaimed(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOwnerClaimed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOwnerClaimed();
            return result;
        }
    }
    async listAdmins(): Promise<Array<Admin>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAdmins();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAdmins();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllFaqs(): Promise<Array<Faq>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllFaqs();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllFaqs();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllProducts();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllProducts();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPageViews(): Promise<Array<RouteViews>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPageViews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPageViews();
            return result;
        }
    }
    async listPublishedFaqs(arg0: bigint): Promise<Array<Faq>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPublishedFaqs(arg0);
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPublishedFaqs(arg0);
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPublishedProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPublishedProducts();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPublishedProducts();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSubmissions(arg0: SubmissionFilter): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubmissions(to_candid_SubmissionFilter_n58(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubmissions(to_candid_SubmissionFilter_n58(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordPageView(arg0: string): Promise<RecordViewResult> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPageView(arg0);
                return from_candid_RecordViewResult_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPageView(arg0);
            return from_candid_RecordViewResult_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdmin(arg0);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async setAdminRole(arg0: Principal, arg1: AdminRole): Promise<Admin | null> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminRole(arg0, to_candid_AdminRole_n12(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminRole(arg0, to_candid_AdminRole_n12(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async setFaqState(arg0: bigint, arg1: PublishState): Promise<Faq | null> {
        if (this.processError) {
            try {
                const result = await this.actor.setFaqState(arg0, to_candid_PublishState_n67(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFaqState(arg0, to_candid_PublishState_n67(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async setProductState(arg0: bigint, arg1: PublishState): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.setProductState(arg0, to_candid_PublishState_n67(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProductState(arg0, to_candid_PublishState_n67(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async setSubmissionStatus(arg0: bigint, arg1: SubmissionStatus): Promise<Submission | null> {
        if (this.processError) {
            try {
                const result = await this.actor.setSubmissionStatus(arg0, to_candid_SubmissionStatus_n60(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSubmissionStatus(arg0, to_candid_SubmissionStatus_n60(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContact(arg0: ContactInput): Promise<SubmitResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0);
                return from_candid_SubmitResult_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0);
            return from_candid_SubmitResult_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitWaitlist(arg0: WaitlistInput): Promise<SubmitResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitWaitlist(to_candid_WaitlistInput_n71(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SubmitResult_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitWaitlist(to_candid_WaitlistInput_n71(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SubmitResult_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFaq(arg0: bigint, arg1: FaqPatch): Promise<Faq | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFaq(arg0, to_candid_FaqPatch_n73(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFaq(arg0, to_candid_FaqPatch_n73(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: bigint, arg1: ProductPatch): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, await to_candid_ProductPatch_n75(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, await to_candid_ProductPatch_n75(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSiteContent(arg0: SiteContentPatch): Promise<SiteContent> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteContent(to_candid_SiteContentPatch_n77(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SiteContent_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteContent(to_candid_SiteContentPatch_n77(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SiteContent_n46(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AdminRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminRole): AdminRole {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Admin_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Admin): Admin {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Faq_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Faq): Faq {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_PublishState_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublishState): PublishState {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_RecordViewResult_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecordViewResult): RecordViewResult {
    return from_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_SiteContent_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SiteContent): SiteContent {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_SubmissionKind_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionKind): SubmissionKind {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_SubmissionStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionStatus): SubmissionStatus {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_Submission_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Submission): Submission {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_SubmitResult_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmitResult): SubmitResult {
    return from_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Admin]): Admin | null {
    return value.length === 0 ? null : from_candid_Admin_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Faq]): Faq | null {
    return value.length === 0 ? null : from_candid_Faq_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RouteViews]): RouteViews | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Promise<Product | null> {
    return value.length === 0 ? null : await from_candid_Product_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Submission]): Submission | null {
    return value.length === 0 ? null : from_candid_Submission_n49(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    question: string;
    sortOrder: bigint;
    createdAt: _Timestamp;
    answer: string;
    updatedAt: _Timestamp;
    state: _PublishState;
}): {
    id: Id;
    question: string;
    sortOrder: bigint;
    createdAt: Timestamp;
    answer: string;
    updatedAt: Timestamp;
    state: PublishState;
} {
    return {
        id: value.id,
        question: value.question,
        sortOrder: value.sortOrder,
        createdAt: value.createdAt,
        answer: value.answer,
        updatedAt: value.updatedAt,
        state: from_candid_PublishState_n18(_uploadFile, _downloadFile, value.state)
    };
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    sortOrder: bigint;
    link: [] | [string];
    name: string;
    createdAt: _Timestamp;
    description: string;
    updatedAt: _Timestamp;
    state: _PublishState;
    imageKey: [] | [_ExternalBlob];
}): Promise<{
    id: Id;
    sortOrder: bigint;
    link?: string;
    name: string;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    state: PublishState;
    imageKey?: ExternalBlob;
}> {
    return {
        id: value.id,
        sortOrder: value.sortOrder,
        link: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.link)),
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        state: from_candid_PublishState_n18(_uploadFile, _downloadFile, value.state),
        imageKey: record_opt_to_undefined(await from_candid_opt_n26(_uploadFile, _downloadFile, value.imageKey))
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n30(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n34(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    role: _AdminRole;
    email: [] | [string];
    addedAt: _Timestamp;
    isOwner: boolean;
}): {
    principal: Principal;
    role: AdminRole;
    email?: string;
    addedAt: Timestamp;
    isOwner: boolean;
} {
    return {
        principal: value.principal,
        role: from_candid_AdminRole_n39(_uploadFile, _downloadFile, value.role),
        email: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.email)),
        addedAt: value.addedAt,
        isOwner: value.isOwner
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactBody: [] | [string];
    privacyBody: [] | [string];
    heroDescription: [] | [string];
    primaryCtaHref: [] | [string];
    primaryCtaLabel: [] | [string];
    philosophyTitle: [] | [string];
    contactTitle: [] | [string];
    philosophyBody: [] | [string];
    aboutTitle: [] | [string];
    waitlistTitle: [] | [string];
    secondaryCtaHref: [] | [string];
    updatedAt: _Timestamp;
    approachBody: [] | [string];
    aboutBody: [] | [string];
    termsBody: [] | [string];
    approachTitle: [] | [string];
    heroHeadline: [] | [string];
    secondaryCtaLabel: [] | [string];
    footerText: [] | [string];
    waitlistBody: [] | [string];
}): {
    contactBody?: string;
    privacyBody?: string;
    heroDescription?: string;
    primaryCtaHref?: string;
    primaryCtaLabel?: string;
    philosophyTitle?: string;
    contactTitle?: string;
    philosophyBody?: string;
    aboutTitle?: string;
    waitlistTitle?: string;
    secondaryCtaHref?: string;
    updatedAt: Timestamp;
    approachBody?: string;
    aboutBody?: string;
    termsBody?: string;
    approachTitle?: string;
    heroHeadline?: string;
    secondaryCtaLabel?: string;
    footerText?: string;
    waitlistBody?: string;
} {
    return {
        contactBody: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.contactBody)),
        privacyBody: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.privacyBody)),
        heroDescription: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.heroDescription)),
        primaryCtaHref: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.primaryCtaHref)),
        primaryCtaLabel: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.primaryCtaLabel)),
        philosophyTitle: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.philosophyTitle)),
        contactTitle: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.contactTitle)),
        philosophyBody: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.philosophyBody)),
        aboutTitle: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.aboutTitle)),
        waitlistTitle: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.waitlistTitle)),
        secondaryCtaHref: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.secondaryCtaHref)),
        updatedAt: value.updatedAt,
        approachBody: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.approachBody)),
        aboutBody: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.aboutBody)),
        termsBody: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.termsBody)),
        approachTitle: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.approachTitle)),
        heroHeadline: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.heroHeadline)),
        secondaryCtaLabel: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.secondaryCtaLabel)),
        footerText: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.footerText)),
        waitlistBody: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.waitlistBody))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    status: _SubmissionStatus;
    kind: _SubmissionKind;
    name: string;
    createdAt: _Timestamp;
    email: string;
    updatedAt: _Timestamp;
    message: [] | [string];
}): {
    id: Id;
    status: SubmissionStatus;
    kind: SubmissionKind;
    name: string;
    createdAt: Timestamp;
    email: string;
    updatedAt: Timestamp;
    message?: string;
} {
    return {
        id: value.id,
        status: from_candid_SubmissionStatus_n51(_uploadFile, _downloadFile, value.status),
        kind: from_candid_SubmissionKind_n53(_uploadFile, _downloadFile, value.kind),
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        updatedAt: value.updatedAt,
        message: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.message))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: null;
} | {
    draft: null;
}): PublishState {
    return "published" in value ? PublishState.published : "draft" in value ? PublishState.draft : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: null;
} | {
    editor: null;
} | {
    viewer: null;
}): AdminRole {
    return "owner" in value ? AdminRole.owner : "editor" in value ? AdminRole.editor : "viewer" in value ? AdminRole.viewer : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    handled: null;
} | {
    read: null;
}): SubmissionStatus {
    return "new" in value ? SubmissionStatus.new : "handled" in value ? SubmissionStatus.handled : "read" in value ? SubmissionStatus.read : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contact: null;
} | {
    waitlist: null;
}): SubmissionKind {
    return "contact" in value ? SubmissionKind.contact : "waitlist" in value ? SubmissionKind.waitlist : value;
}
function from_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recorded: _RouteViews;
} | {
    ignored: null;
}): {
    __kind__: "recorded";
    recorded: RouteViews;
} | {
    __kind__: "ignored";
    ignored: null;
} {
    return "recorded" in value ? {
        __kind__: "recorded",
        recorded: value.recorded
    } : "ignored" in value ? {
        __kind__: "ignored",
        ignored: value.ignored
    } : value;
}
function from_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    created: _Submission;
} | {
    duplicate: _Submission;
}): {
    __kind__: "created";
    created: Submission;
} | {
    __kind__: "duplicate";
    duplicate: Submission;
} {
    return "created" in value ? {
        __kind__: "created",
        created: from_candid_Submission_n49(_uploadFile, _downloadFile, value.created)
    } : "duplicate" in value ? {
        __kind__: "duplicate",
        duplicate: from_candid_Submission_n49(_uploadFile, _downloadFile, value.duplicate)
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Admin>): Array<Admin> {
    return value.map((x)=>from_candid_Admin_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Faq>): Array<Faq> {
    return value.map((x)=>from_candid_Faq_n16(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n23(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Submission>): Array<Submission> {
    return value.map((x)=>from_candid_Submission_n49(_uploadFile, _downloadFile, x));
}
function to_candid_AdminRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdminRole): _AdminRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FaqPatch_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FaqPatch): _FaqPatch {
    return to_candid_record_n74(_uploadFile, _downloadFile, value);
}
async function to_candid_ProductInput_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductInput): Promise<_ProductInput> {
    return await to_candid_record_n21(_uploadFile, _downloadFile, value);
}
async function to_candid_ProductPatch_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductPatch): Promise<_ProductPatch> {
    return await to_candid_record_n76(_uploadFile, _downloadFile, value);
}
function to_candid_PublishState_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublishState): _PublishState {
    return to_candid_variant_n68(_uploadFile, _downloadFile, value);
}
function to_candid_SiteContentPatch_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SiteContentPatch): _SiteContentPatch {
    return to_candid_record_n78(_uploadFile, _downloadFile, value);
}
function to_candid_SubmissionFilter_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionFilter): _SubmissionFilter {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_SubmissionKind_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionKind): _SubmissionKind {
    return to_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function to_candid_SubmissionStatus_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionStatus): _SubmissionStatus {
    return to_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_WaitlistInput_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WaitlistInput): _WaitlistInput {
    return to_candid_record_n72(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sortOrder: bigint;
    link?: string;
    name: string;
    description: string;
    imageKey?: ExternalBlob;
}): Promise<{
    sortOrder: bigint;
    link: [] | [string];
    name: string;
    description: string;
    imageKey: [] | [_ExternalBlob];
}> {
    return {
        sortOrder: value.sortOrder,
        link: value.link ? candid_some(value.link) : candid_none(),
        name: value.name,
        description: value.description,
        imageKey: value.imageKey ? candid_some(await to_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.imageKey)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: SubmissionStatus;
    kind?: SubmissionKind;
}): {
    status: [] | [_SubmissionStatus];
    kind: [] | [_SubmissionKind];
} {
    return {
        status: value.status ? candid_some(to_candid_SubmissionStatus_n60(_uploadFile, _downloadFile, value.status)) : candid_none(),
        kind: value.kind ? candid_some(to_candid_SubmissionKind_n62(_uploadFile, _downloadFile, value.kind)) : candid_none()
    };
}
function to_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    note?: string;
    email: string;
}): {
    name: string;
    note: [] | [string];
    email: string;
} {
    return {
        name: value.name,
        note: value.note ? candid_some(value.note) : candid_none(),
        email: value.email
    };
}
function to_candid_record_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    question?: string;
    sortOrder?: bigint;
    answer?: string;
}): {
    question: [] | [string];
    sortOrder: [] | [bigint];
    answer: [] | [string];
} {
    return {
        question: value.question ? candid_some(value.question) : candid_none(),
        sortOrder: value.sortOrder ? candid_some(value.sortOrder) : candid_none(),
        answer: value.answer ? candid_some(value.answer) : candid_none()
    };
}
async function to_candid_record_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sortOrder?: bigint;
    link?: string;
    name?: string;
    description?: string;
    imageKey?: ExternalBlob;
}): Promise<{
    sortOrder: [] | [bigint];
    link: [] | [string];
    name: [] | [string];
    description: [] | [string];
    imageKey: [] | [_ExternalBlob];
}> {
    return {
        sortOrder: value.sortOrder ? candid_some(value.sortOrder) : candid_none(),
        link: value.link ? candid_some(value.link) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        imageKey: value.imageKey ? candid_some(await to_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.imageKey)) : candid_none()
    };
}
function to_candid_record_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactBody?: string;
    privacyBody?: string;
    heroDescription?: string;
    primaryCtaHref?: string;
    primaryCtaLabel?: string;
    philosophyTitle?: string;
    contactTitle?: string;
    philosophyBody?: string;
    aboutTitle?: string;
    waitlistTitle?: string;
    secondaryCtaHref?: string;
    approachBody?: string;
    aboutBody?: string;
    termsBody?: string;
    approachTitle?: string;
    heroHeadline?: string;
    secondaryCtaLabel?: string;
    footerText?: string;
    waitlistBody?: string;
}): {
    contactBody: [] | [string];
    privacyBody: [] | [string];
    heroDescription: [] | [string];
    primaryCtaHref: [] | [string];
    primaryCtaLabel: [] | [string];
    philosophyTitle: [] | [string];
    contactTitle: [] | [string];
    philosophyBody: [] | [string];
    aboutTitle: [] | [string];
    waitlistTitle: [] | [string];
    secondaryCtaHref: [] | [string];
    approachBody: [] | [string];
    aboutBody: [] | [string];
    termsBody: [] | [string];
    approachTitle: [] | [string];
    heroHeadline: [] | [string];
    secondaryCtaLabel: [] | [string];
    footerText: [] | [string];
    waitlistBody: [] | [string];
} {
    return {
        contactBody: value.contactBody ? candid_some(value.contactBody) : candid_none(),
        privacyBody: value.privacyBody ? candid_some(value.privacyBody) : candid_none(),
        heroDescription: value.heroDescription ? candid_some(value.heroDescription) : candid_none(),
        primaryCtaHref: value.primaryCtaHref ? candid_some(value.primaryCtaHref) : candid_none(),
        primaryCtaLabel: value.primaryCtaLabel ? candid_some(value.primaryCtaLabel) : candid_none(),
        philosophyTitle: value.philosophyTitle ? candid_some(value.philosophyTitle) : candid_none(),
        contactTitle: value.contactTitle ? candid_some(value.contactTitle) : candid_none(),
        philosophyBody: value.philosophyBody ? candid_some(value.philosophyBody) : candid_none(),
        aboutTitle: value.aboutTitle ? candid_some(value.aboutTitle) : candid_none(),
        waitlistTitle: value.waitlistTitle ? candid_some(value.waitlistTitle) : candid_none(),
        secondaryCtaHref: value.secondaryCtaHref ? candid_some(value.secondaryCtaHref) : candid_none(),
        approachBody: value.approachBody ? candid_some(value.approachBody) : candid_none(),
        aboutBody: value.aboutBody ? candid_some(value.aboutBody) : candid_none(),
        termsBody: value.termsBody ? candid_some(value.termsBody) : candid_none(),
        approachTitle: value.approachTitle ? candid_some(value.approachTitle) : candid_none(),
        heroHeadline: value.heroHeadline ? candid_some(value.heroHeadline) : candid_none(),
        secondaryCtaLabel: value.secondaryCtaLabel ? candid_some(value.secondaryCtaLabel) : candid_none(),
        footerText: value.footerText ? candid_some(value.footerText) : candid_none(),
        waitlistBody: value.waitlistBody ? candid_some(value.waitlistBody) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdminRole): {
    owner: null;
} | {
    editor: null;
} | {
    viewer: null;
} {
    return value == AdminRole.owner ? {
        owner: null
    } : value == AdminRole.editor ? {
        editor: null
    } : value == AdminRole.viewer ? {
        viewer: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionStatus): {
    new: null;
} | {
    handled: null;
} | {
    read: null;
} {
    return value == SubmissionStatus.new ? {
        new_: null
    } : value == SubmissionStatus.handled ? {
        handled: null
    } : value == SubmissionStatus.read ? {
        read: null
    } : value;
}
function to_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionKind): {
    contact: null;
} | {
    waitlist: null;
} {
    return value == SubmissionKind.contact ? {
        contact: null
    } : value == SubmissionKind.waitlist ? {
        waitlist: null
    } : value;
}
function to_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublishState): {
    published: null;
} | {
    draft: null;
} {
    return value == PublishState.published ? {
        published: null
    } : value == PublishState.draft ? {
        draft: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
